/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        light: {
          primary: '#0057ce',
          onPrimary: '#ffffff',
          primaryContainer: '#dae2ff',
          onPrimaryContainer: '#001946',
          primaryFixed: '#dae2ff',
          onPrimaryFixed: '#001946',
          primaryFixedDim: '#b1c5ff',
          onPrimaryFixedVariant: '#00419e',
          secondary: '#bc004f',
          onSecondary: '#ffffff',
          secondaryContainer: '#ffd9de',
          onSecondaryContainer: '#3f0016',
          secondaryFixed: '#ffd9de',
          onSecondaryFixed: '#3f0016',
          secondaryFixedDim: '#ffb2bf',
          onSecondaryFixedVariant: '#90003b',
          tertiary: '#2a6c00',
          onTertiary: '#ffffff',
          tertiaryContainer: '#7fff38',
          onTertiaryContainer: '#082100',
          tertiaryFixed: '#7fff38',
          onTertiaryFixed: '#082100',
          tertiaryFixedDim: '#60e200',
          onTertiaryFixedVariant: '#1e5100',
          error: '#b4271f',
          errorContainer: '#ffdad5',
          onError: '#ffffff',
          onErrorContainer: '#410001',
          background: '#fefbff',
          onBackground: '#1b1b1f',
          outline: '#757780',
          inverseOnSurface: '#f2f0f4',
          inverseSurface: '#303034',
          inversePrimary: '#b1c5ff',
          shadow: '#000000',
          surfaceTint: '#0057ce',
          outlineVariant: '#c5c6d0',
          scrim: '#000000',
          surface: '#fbf8fd',
          onSurface: '#1b1b1f',
          surfaceVariant: '#e1e2ec',
          onSurfaceVariant: '#44464f',
          surfaceContainerHighest: '#e4e2e6',
          surfaceContainerHigh: '#e9e7ec',
          surfaceContainer: '#efedf1',
          surfaceContainerLow: '#f5f3f7',
          surfaceContainerLowest: '#ffffff',
          surfaceDim: '#dbd9dd',
          surfaceBright: '#fbf8fd',
          verification: "#d9d9d9"
        },
        dark: {
          primary: '#b1c5ff',
          onPrimary: '#002c70',
          primaryContainer: '#00419e',
          onPrimaryContainer: '#dae2ff',
          primaryFixed: '#dae2ff',
          onPrimaryFixed: '#001946',
          primaryFixedDim: '#b1c5ff',
          onPrimaryFixedVariant: '#00419e',
          secondary: '#ffb2bf',
          onSecondary: '#660027',
          secondaryContainer: '#90003b',
          onSecondaryContainer: '#ffd9de',
          secondaryFixed: '#ffd9de',
          onSecondaryFixed: '#3f0016',
          secondaryFixedDim: '#ffb2bf',
          onSecondaryFixedVariant: '#90003b',
          tertiary: '#60e200',
          onTertiary: '#123800',
          tertiaryContainer: '#1e5100',
          onTertiaryContainer: '#7fff38',
          tertiaryFixed: '#7fff38',
          onTertiaryFixed: '#082100',
          tertiaryFixedDim: '#60e200',
          onTertiaryFixedVariant: '#1e5100',
          error: '#ffb4aa',
          errorContainer: '#910809',
          onError: '#690003',
          onErrorContainer: '#ffdad5',
          background: '#1b1b1f',
          onBackground: '#e4e2e6',
          outline: '#8f9099',
          inverseOnSurface: '#1b1b1f',
          inverseSurface: '#e4e2e6',
          inversePrimary: '#0057ce',
          shadow: '#000000',
          surfaceTint: '#b1c5ff',
          outlineVariant: '#44464f',
          scrim: '#000000',
          surface: '#121316',
          onSurface: '#c7c6ca',
          surfaceVariant: '#44464f',
          onSurfaceVariant: '#c5c6d0',
          surfaceContainerHighest: '#343438',
          surfaceContainerHigh: '#292a2d',
          surfaceContainer: '#1f1f23',
          surfaceContainerLow: '#1b1b1f',
          surfaceContainerLowest: '#0d0e11',
          surfaceDim: '#121316',
          surfaceBright: '#39393c',
        },
      },

      screens: {
        xs: '350px',
        // => @media (min-width: 400px) { ... }
        sm: '640px',
        // => @media (min-width: 640px) { ... }

        md: '768px',
        // => @media (min-width: 768px) { ... }

        lg: '1024px',
        // => @media (min-width: 1024px) { ... }

        xl: '1280px',
        // => @media (min-width: 1280px) { ... }

        '2xl': '1536px',
        // => @media (min-width: 1536px) { ... }
      },
    },
  },
  plugins: [],
};
