import { nanoid } from "nanoid";
import {
  BUSINESS_OPTIONS,
  COMPANY_TYPE,
  CORPORATE_ACCOUNT_TYPE,
} from "../static/static_const.js";

export const CorporateField = [
  {
    name: "corporateAccountType",
    label: "Account Type (खाताको प्रकार)",
    disabled: true,
    type: "select",
    col: 12,
    sm: 4,
    required: "Please select account type",
    placeholder: "Select account type",
    options: CORPORATE_ACCOUNT_TYPE,
    id: nanoid(),
  },
  {
    name: "companyName",
    label: "Company Name (कम्पनीको नाम)",
    type: "text",
    col: 12,
    sm: 4,
    required: "Please enter company name",
    placeholder: "Enter company name",
    id: nanoid(),
    maxLength: 100,
    able: true,
  },
  {
    name: "companyCeoName",
    label: "Company CEO Name (प्रमुख कार्यकारी अधिकृतको नाम)",
    type: "onlyText",
    col: 12,
    sm: 4,
    required: "Please enter company CEO name",
    placeholder: "Enter CEO name",
    id: nanoid(),
    maxLength: 75,
  },
  {
    name: "companySecretaryName",
    label: "Company Secretary Name (कम्पनी सचिवको नाम)",
    type: "onlyText",
    col: 12,
    sm: 4,
    required: "Please enter name of company secretary",
    placeholder: "Enter secretary name",
    id: nanoid(),
    maxLength: 75,
  },
  {
    name: "companyType",
    label: "Company Type (कम्पनीको प्रकार)",
    type: "select",
    options: COMPANY_TYPE,
    col: 12,
    sm: 4,
    required: "Please select type of company (e.g. PUBLIC, PRIVATE, etc.)",
    placeholder: "Select company type",
    id: nanoid(),
  },
  {
    name: "contactNumber",
    label: "Contact Number (सम्पर्क नम्बर)",
    type: "mobileNo",
    col: 12,
    sm: 4,
    required: "Please enter company contact number",
    placeholder: "Enter contact number",
    maxLength: 21,
    minLength: 10,
    id: nanoid(),
  },
  {
    name: "countryReg",
    label: "Country of Registration (दर्ताको देश)",
    type: "select",
    col: 12,
    sm: 4,
    required: "Please select country of registration",
    placeholder: "Select country Of registration",
    options: [
      {
        value: "Nepal",
        label: "Nepal",
      },
    ],
    id: nanoid(),
  },
  {
    name: "incorporationDate",
    label: "Incorporation Date (समावेश मिति) (B.S.)",
    type: "date-picker-citizen",
    col: 12,
    sm: 8,
    dualDate: true,
    engLabel: "Incorporation Date (समावेश मिति) (A.D.)",
    engPlaceholder: "Select Incorporation (A.D.)",
    dualDate: true,
    required: true,
    placeholder: "Select incorporation date",
    id: nanoid(),
  },
  {
    name: "registrationNo",
    label: "Registration Number (दर्ता नम्बर)",
    type: "text",
    col: 12,
    sm: 4,
    required: "Please enter company registration number",
    placeholder: "Enter registration number",
    id: nanoid(),
  },
  {
    name: "registrationOffice",
    label: "Registration Office (दर्ता कार्यालय)",
    type: "text",
    col: 12,
    sm: 4,
    required: "Please enter office where company is registered",
    placeholder: "Enter registration office",
    id: nanoid(),
    maxLength: 75,
  },
  {
    name: "registrationDate",
    label: "Registration Date (दर्ता मिति) (B.S.)",
    type: "date-picker-citizen",
    col: 12,
    sm: 8,
    dualDate: true,
    engLabel: "Registration Date (दर्ता मिति) (A.D.)",
    engPlaceholder: "Select registration date (A.D.)",
    dualDate: true,
    required: true,
    placeholder: "Select registration date",
    id: nanoid(),
  },
  {
    name: "panNo",
    label: "PAN Number (प्यान नम्बर)",
    type: "text",
    col: 12,
    sm: 4,
    required: "Please enter company PAN number",
    placeholder: "Enter PAN number",
    id: nanoid(),
    maxLength: 10,
  },
  {
    name: "businessType",
    label: "Business Type (व्यापार प्रकार)",
    type: "select",
    options: BUSINESS_OPTIONS,
    col: 12,
    sm: 4,
    required:
      "Please select type of business company (e.g. MANUFACTURING, TRADING, etc.)",
    placeholder: "Select business type",
    id: nanoid(),
  },
  {
    name: "workArea",
    label: "Work Area (कार्य क्षेत्र)",
    type: "text",
    col: 12,
    sm: 4,
    placeholder: "Enter work place",
    required: "Please enter area of work",
    id: nanoid(),
    maxLength: 75,
  },
  {
    name: "vatRegistration",
    label: "VAT Registration No (मूल्य अभिबृद्धि कर दर्ता नं.)",
    type: "vatNo",
    col: 12,
    sm: 4,
    placeholder: "Enter VAT Registration No",
    // required: "Please enter area of work",
    id: nanoid(),
    maxLength: 15,
  },
  {
    name: "nrbRegistration",
    label: "NRB Registration No (नेपाल राष्ट्र बैंकमा दर्ता भएको भए दर्ता नं.)",
    type: "citizenship",
    col: 12,
    sm: 4,
    placeholder: "Enter NRB Registration No",
    // required: "Please enter area of work",
    id: nanoid(),
    maxLength: 15,
  },
  {
    name: "nrbApproval",
    label: "NRB Approval Date (नेपाल राष्ट्र बैंकको स्वीकृत मिति) (B.S.)",
    type: "date-picker-citizen",
    col: 12,
    sm: 8,
    dualDate: true,
    engLabel: "NRB Approval Date (नेपाल राष्ट्र बैंकको स्वीकृत मिति) (A.D.)",
    engPlaceholder: "Enter NRB Approval Date (A.D.)",
    dualDate: true,
    placeholder: "Enter NRB Approval Date",
    // required: "Please enter area of work",
    id: nanoid(),
    maxLength: 75,
  },

  {
    name: "isMF",
    label: "Is Mutual Fund? (म्युचुअल फण्ड हो?)",
    type: "switch",
    col: 12,
    required: "Please specify whether company is mutual fund or not",
    id: nanoid(),
  },
  {
    name: "isSubsidiary",
    label: "Is Subsidiary? (सहायक हो?)",
    type: "switch",
    col: 12,
    required: "Please specify whether company is subsidiary or not",
    id: nanoid(),
  },
  {
    name: "mainCompanyName",
    label: "Main Company Name (मुख्य कम्पनी नाम)",
    placeholder: "Enter main company name",
    type: "text",
    col: 12,
    sm: 4,
    required: "Please enter main company name",
    id: nanoid(),
    watchFor: "isSubsidiary",
    dependentAction: {
      type: "HIDDEN",
      condition: false,
    },
    maxLength: 75,
  },
  {
    name: "isListed",
    label: "Is Company Listed? (कम्पनी सूचीबद्ध छ?)",
    type: "switch",
    col: 12,
    required: "Please specify whether company is listed or not",
    id: nanoid(),
  },
  {
    name: "listingDate",
    label: "Listing Date (सूचीकरण मिति) (B.S.)",
    type: "date-picker-citizen",
    col: 12,
    sm: 8,
    dualDate: true,
    engLabel: "Listing Date (सूचीकरण मिति) (A.D.)",
    engPlaceholder: "Select listed date (A.D.)",
    dualDate: true,

    placeholder: "Select listed date",
    required: true,
    id: nanoid(),
    watchFor: "isListed",
    dependentAction: {
      type: "HIDDEN",
      condition: false,
    },
  },
];
