export const FETCH_PAGINATED_SELECT = 'FETCH_PAGINATED_SELECT';
export const FETCH_PAGINATED_SUMMARY_SELECT = 'FETCH_PAGINATED_SUMMARY_SELECT';

export const FETCH_PAGINATED_SELECT_FAILED = 'FETCH_PAGINATED_SELECT_FAILED';
export const PAGINATED_SELECT_PROCESSING = 'PAGINATED_SELECT_PROCESSING';
export const PAGINATED_SELECT_DATA_CLEAR = 'PAGINATED_SELECT';
export const PAGINATED_SELECT_DATA_UPDATE = 'PAGINATED_SELECT_DATA_UPDATE';
export const UPDATE_SINGLE_ROW = 'UPDATE_SINGLE_ROW';
export const REMOVE_ARRAY_OF_DATA = 'REMOVE_ARRAY_OF_DATA';

export const FETCH_DATA = 'FETCH_DATA';
export const CLEAR_DATA = 'CLEAR_DATA';
export const POST_DATA = 'POST_DATA';
export const PATCH_DATA = 'PATCH_DATA';
export const PATCH_PARENT_DATA = 'PATCH_PARENT_DATA';
export const PROCESSING = 'GENERICPROCESSING';
export const DELETE_DATA = 'DELETE_DATA';
export const EDIT_DATA = 'EDIT_DATA';
