import { DISTRICTS } from '../basicInputData'

export const DocumentField = [
  {
    name: "documentType",
    label: "Select Document Type",
    md: 3,
    sm: 6,
    lg: 4,
    xs: 12,
    required: true,
    type: "dropDown",
    options: [
      { id: 1, value: "CZ", label: "Citizenship" },
      { id: 2, value: "pan", label: "Pan Card" },
      { id: 3, value: "PT", label: "Passport" },
      { id: 4, value: "BC", label: "Birth Certificate" },
      { id: 4, value: "TP", label: "Thumb Print" },
      { id: 4, value: "SG", label: "Signature" },
      { id: 4, value: "PP", label: "Passport Size Picture" },
    ],
  },
]

export const citizenshipField = [
  {
    name: "documentType",
    label: "Select Document Type",
    md: 4,
    sm: 6,
    lg: 4,
    xs: 12,
    required: true,
    type: "dropDown",
   
    options: [
      { id: 1, value: "GCZ", label: "Gaurdian Citizenship" },
      { id: 1, value: "CZ", label: "Citizenship" },
      { id: 2, value: "panCard", label: "Pan Card" },
      { id: 3, value: "PT", label: "Passport" },
      { id: 4, value: "birthCertificate", label: "Birth Certificate" },
    ],
  },
  {
    name: "documentNo",
    label: "Citizenship No.",
    md: 4,
    sm: 6,
    lg: 4,
    xs: 12,
    required: true,
    type: "text",
  },
  {
    name: "issuedDistrict",
    label: "Citizenship Issued District",
    md: 4,
    sm: 12,
    lg: 4,
    xs: 12,
    required: true,
    type: "dropDown",
    options: DISTRICTS,
  },
  {
    name: "issuedDate",
    nameNep: "issuedDateBS",
    label: "Citizenship Issued Date (B.S)",
    engMd: 4,
    engSm: 12,
    nepMd: 6,
    nepSm: 12,
    md: 12,
    sm: 12,
    disableFuture: true,
    engLabel: "Citizenship Issued Date (A.D.)",
    nepaliLabel: "Citizenship Issued Date (B.S.)",
    required: true,
    type: "dualDate",
  },
  {
    md: 6,
    sm: 6,
    lg: 6,
    xs: 12,
    required: true,
    type: "documentUpload",
    title: "Front Side",
    name: "citizenshipFront",
  },
  {
    md: 6,
    sm: 6,
    lg: 6,
    xs: 12,
    required: true,
    type: "documentUpload",
    title: "Back Side",
    name: "citizenshipBack",
  },
]

export const passportField = [
  {
    name: "documentType",
    label: "Select Document Type",
    md: 4,
    sm: 12,
    lg: 4,
    xs: 12,
    required: true,
    type: "dropDown",
    options: [
      { id: 1, value: "CZ", label: "Citizenship" },
      { id: 2, value: "panCard", label: "Pan Card" },
      { id: 3, value: "PT", label: "Passport" },
      { id: 4, value: "birthCertificate", label: "Birth Certificate" },
    ],
  },
  {
    name: "passportNumber",
    label: "Passport Number",
    md: 4,
    sm: 12,
    lg: 4,
    xs: 12,
    required: true,
    type: "text",
  },
  {
    name: "passportDistrict",
    label: "Passport Issued District",
    md: 4,
    sm: 12,
    lg: 4,
    xs: 12,
    required: true,
    type: "dropDown",
    options: DISTRICTS,
  },
  {
    name: "passportIssuedDate",
    label: "Passport Issued Date",
    nameNep: "issuedDateBS",
    label: "Passport Issued Date (B.S)",
    engMd: 4,
    engSm: 12,
    nepMd: 4,
    nepSm: 12,
    md: 12,
    sm: 12,
    disableFuture: true,
    engLabel: "Passport Issued Date (A.D.)",
    nepaliLabel: "Passport Issued Date (B.S.)",
    required: true,
    type: "dualDate",
  },
  {
    name: "passportExpiryDateDate",
    label: "Passport Expiry Date",
    md: 4,
    sm: 12,
    lg: 4,
    xs: 12,
    required: true,
    type: "datePicker",
  },
  {
    md: 12,
    sm: 12,
    lg: 12,
    xs: 12,
    required: true,
    type: "documentUpload",
    title: "Passport Photo",
  },
]

export const passportPicField = [
  {
    name: "documentType",
    label: "Select Document Type",
    md: 3,
    sm: 6,
    lg: 4,
    xs: 12,
    required: true,
    type: "dropDown",
    options: [
      { id: 1, value: "citizenship", label: "Citizenship" },
      { id: 2, value: "panCard", label: "Pan Card" },
      { id: 3, value: "passport", label: "Passport" },
      { id: 4, value: "BC", label: "Birth Certificate" },
    ],
  },
  {
    md: 12,
    sm: 12,
    lg: 12,
    xs: 12,
    required: true,
    type: "documentUpload",
    title: "Passport Size Photo",
  },
]

export const panField = [
  {
    name: "documentType",
    label: "Select Document Type",
    md: 3,
    sm: 6,
    lg: 4,
    xs: 12,
    required: true,
    type: "dropDown",
    options: [
      { id: 1, value: "citizenship", label: "Citizenship" },
      { id: 2, value: "panCard", label: "Pan Card" },
      { id: 3, value: "passport", label: "Passport" },
      { id: 4, value: "birthCertificate", label: "Birth Certificate" },
    ],
  },

  {
    name: "documentNo",
    label: "PAN No.",
    md: 4,
    sm: 6,
    lg: 4,
    xs: 12,
    required: true,
    type: "text",
  },
  {
    name: "issuedDistrict",
    label: "Pan Issued District",
    md: 4,
    sm: 12,
    lg: 4,
    xs: 12,
    required: true,
    type: "dropDown",
    options: DISTRICTS,
  },
  {
    name: "issuedDate",
    nameNep: "issuedDateBS",
    label: "PAN Issued Date (B.S)",
    engMd: 4,
    engSm: 12,
    nepMd: 6,
    nepSm: 12,
    md: 12,
    sm: 12,
    disableFuture: true,
    engLabel: "PAN Issued Date (A.D.)",
    nepaliLabel: "PAN Issued Date (B.S.)",
    required: true,
    type: "dualDate",
  },
  {
    md: 12,
    sm: 12,
    lg: 12,
    xs: 12,
    required: true,
    name: "panDocument",
    type: "documentUpload",
    title: "Pan Card Photo",
  },
]

export const birthCertificateField = [
  {
    name: "documentType",
    label: "Select Document Type",
    md: 3,
    sm: 6,
    lg: 4,
    xs: 12,
    required: true,
    type: "dropDown",
    options: [
      { id: 1, value: "citizenship", label: "Citizenship" },
      { id: 2, value: "panCard", label: "Pan Card" },
      { id: 3, value: "passport", label: "Passport" },
      { id: 4, value: "BC", label: "Birth Certificate" },
    ],
  },
  {
    md: 12,
    sm: 12,
    lg: 12,
    xs: 12,
    required: true,
    type: "documentUpload",
    name: "BC",
    title: "Birth certificate Photo",
  },
]

export const thumbField = [
  {
    name: "documentType",
    label: "Select Document Type",
    md: 3,
    sm: 6,
    lg: 4,
    xs: 12,
    required: true,
    type: "dropDown",
    options: [
      { id: 1, value: "citizenship", label: "Citizenship" },
      { id: 2, value: "panCard", label: "Pan Card" },
      { id: 3, value: "passport", label: "Passport" },
      { id: 4, value: "BC", label: "Birth Certificate" },
    ],
  },
  {
    name: "LTP",
    md: 12,
    sm: 12,
    lg: 12,
    xs: 12,
    required: true,
    type: "documentUpload",
    title: "Thumb Print Left",
  },
  {
    name: "RTP",
    md: 12,
    sm: 12,
    lg: 12,
    xs: 12,
    required: true,
    type: "documentUpload",
    title: "Thumb Print Right",
  },
]

export const signatureField = [
  {
    name: "documentType",
    label: "Select Document Type",
    md: 3,
    sm: 6,
    lg: 4,
    xs: 12,
    required: true,
    type: "dropDown",
    options: [
      { id: 1, value: "citizenship", label: "Citizenship" },
      { id: 2, value: "panCard", label: "Pan Card" },
      { id: 3, value: "passport", label: "Passport" },
      { id: 4, value: "BC", label: "Birth Certificate" },
    ],
  },
  {
    name: "SG",
    md: 12,
    sm: 12,
    lg: 12,
    xs: 12,
    required: true,
    type: "documentUpload",
    title: "Signature",
  },
]